[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.158.0"
  HUGO_ENV     = "production"

[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"
